language: python

python: "3.6"

sudo: false

install:
  - 'curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_VERSION=1.0.9 python'
  - source $HOME/.poetry/env
  - which poetry
  - poetry install -vv
# command to run tests
script:
  - poetry run pytest -vv ./tests
