language: python

python: "3.6"

sudo: false

cache:
  - directories:
      - $HOME/.pip-cache
  - apt

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
# command to run tests
script:
- py.test -vv tests/*
